[workspace]
resolver="2"
members=[
    "crates/base",
    "crates/client"
]

[workspace.dependencies]
bevy = { version = "0.10.1", default-features = false }
shrinkwraprs = "0.3.0"
serde = "1.0.163"
serde_json = "1.0.96"